export const ADD_COACH = 'ADD_COACH';
export const DELETE_COACH = 'DELETE_COACH';
export const EDIT_COACH = 'EDIT_COACH';
export const ADD_CHAMPIONSHIP = 'ADD_CHAMPIONSHIP';
export const DELETE_CHAMPIONSHIP = 'DELETE_CHAMPIONSHIP';
export const EDIT_CHAMPIONSHIP = 'EDIT_CHAMPIONSHIP';
